-- https://school.programmers.co.kr/learn/courses/30/lessons/151139
SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
    )
    and START_DATE BETWEEN '2022-08-01' and '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH, CAR_ID DESC