-- 첫 코드
-- 코드를 입력하세요
SELECT DISTINCT o.CAR_ID, IFNULL(n.AVAILABILITY, '대여 가능') as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY o
LEFT JOIN (
    SELECT CAR_ID, '대여중' as AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' and END_DATE >= '2022-10-16' 
    GROUP BY CAR_ID
) n
on o.CAR_ID = n.CAR_ID
ORDER BY o.CAR_ID DESC

-- MAX, CASE문 사용
SELECT CAR_ID, CASE
    WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) = 1 THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC