-- https://school.programmers.co.kr/learn/courses/30/lessons/144855
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES 
FROM BOOK_SALES
    INNER JOIN BOOK
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY